# Triggered on a new release git tag pushed, starts the final steps of a release.
#
# Steps currently include
#   1. Updating master changelogs using JS script

name: Finalize Release

on:
  workflow_dispatch:
  push:
    branches:
    - 'release/*'
    paths:
    - '**/CHANGELOG.md'

jobs:
  finalize:
    name: Cherry-pick Changelogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.IMJS_ADMIN_GH_TOKEN }}
          ref: ${{ github.ref }} # checkouts the branch that triggered the workflow
          fetch-depth: 0
      - name: Run update-changelogs.mjs
        run: |
          echo "got here"
        shell: bash {0}
